### ISSUE TITLE
ExactOnline.Client.Sdk.Sync /sync/SalesOrder/SalesOrders does not sync SalesOrderLines

### ISSUE THREAD

**Issue by d-gunsing** [fretje/exactonline-api-dotnet-client#5]
/sync/SalesOrder/SalesOrders does not update the SalesOrderLines table. The SalesOrderLine data is actually part of the /sync/SalesOrder/SalesOrders endpoint, but only the SalesOrder database table is updated.

The same issue is also present for /sync/CRM/Quotations (this one also contains QuotatonLines, but these are not stored in the database).

**Comment by fretje** [comment]
Hmm, I see... Syncing only supports one level now. Not sure how this could be implemented to go "multiple levels"...

But I see there's also an [SalesOrderLines](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrderLines) endpoint... as wel as a [QuoatationLines](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkCRMQuotationLines) endpoint. So you still can sync all the tables, right?

**Comment by d-gunsing** [comment]
Technically you could, but the bulk/salesorderlines endpoint (which is what you would have to use to prevent running into the api call limits Exact forces now) does not have a 'Modified' date field. This means you would have to sync the entire SalesOrderLines table every time if you want to keep everything in sync. It isn't possible to only get the 'newest' records that way, or just the changed ones.

**Comment by fretje** [comment]
There is also a Sync SalesOrder endpoint which also returns SalesOrderLines apparently.  

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncSalesOrderSalesOrders

Maybe that one can be used? There is a "Modified" date there...

**Comment by d-gunsing** [comment]
That is the issue I am facing. I am already syncing /sync/SalesOrder/SalesOrders but ExactOnline.Client.Sdk.Sync only syncs SalesOrders, it skips all the included SalesOrderlines (does not store those in the database).
If you sync SalesOrderLines, it goes to the SalesOrderLines endpoint, not SalesOrders.

**Comment by fretje** [comment]
Ohh.. I see... I think I understand what's happening...

It's because the primary key of that table is "orderId", and as that id is the same for all lines (+ the header) of a particular order, there's only one record saved in the database...

I wonder if it would be as easy as changing the DataServiceKey attribute to include the LineNumber as in:

```c#
    [DataServiceKey("OrderID;LineNumber")]
```

Could you maybe test that out? 

I see you will have to add the LineNumber property as well as that one isn't available yet in the SalesOrder Model. There might be more that are missing...

**Comment by d-gunsing** [comment]
If you look at https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncSalesOrderSalesOrders you can see that the SalesOrder model and the SalesOrderLine model is actually both part of /sync/SalesOrder/SalesOrders.

By extending the SalesOrder model with all the SalesOrderLine fields and changing the DataServiceKey won't that mean you get a table with non-unique SalesOrders (every order will appear as many times as there are articles in that order) and every SalesOrder will include 1 SalesOrderLine in the same row?

So every row returned from the sync contains 2 entities, 1 SalesOrder and 1 SalesOrderLine and each should ideally be saved to their corresponding database table.

**Comment by fretje** [comment]
Yes I understand, but that's just how that specific sync endpoint works.

The Sdk.Sync library is just mapping the endpoints one to one onto tables. I don't see how that splitting up could be solved in a generic way...

The SynchronizeWith method is actually filtering out the doubles when dealing with a sync endpoint, as there can sometimes be duplicate entries for the same id (if something has been changed multiple times since the last sync). So that table definitely needs a composite key.

So if you really need the separate tables you could maybe run a query afterwards that splits the table up into 2 separate tables? Or create some views over the table in your database?

Or otherwise there's always the option of doing the syncing manually for that endpoint using the standard (non sync) Sdk and then inserting the records in your database however you want?

**Comment by d-gunsing** [comment]
What I ended up doing is make a new class SalesOrderSalesOrderLines with all the fields from the models SalesOrder and SalesOrderLines and then change the dataservicekey to ID. The endpoint is still /sync/salesorder/salesorders.

`[DataServiceKey("ID")]`

By syncing this you get a new table with all the orders and salesorders combined. The SalesOrder can be found by getting the record where LineNumber == 0 and the articles for that order where LineNumber > 0.

This immediately solved another issue I was having, namely that the SalesOrder field AmountFC was (most of the time) incorrect after syncing compared to the salesorder from the 'normal' endpoint. It turns out that the SDK filters out doubles, so if 5 lines are returned, the first one being the order itself and the other 4 articles from that order, the SDK would use the last one (highest timestamp) and filter out the first 4, thereby setting the order field AmountFC to the value of an article from that order and not the order itself.

I had the same issue with Quotations and SalesInvoices and those sync endpoints both have the lines also embedded and this fixed it for those as well.
